repos:
  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black
  - repo: https://github.com/humitos/mirrors-autoflake
    rev: v1.3
    hooks:
      - id: autoflake
        args:
          [
            -i,
            --remove-all-unused-imports,
            --remove-unused-variables,
            --ignore-init-module-imports,
          ]
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: 'v5.6.4'
    hooks:
    -   id: isort