global:
  template: templates/eid_adha/template.mako
  filters:
    - arabic_only
  group_limit: 100
campaigns:
  - group: Family
    template: templates/eid_adha/family_template.mako
  - group: Close Family
    template: templates/eid_adha/close_template.mako
  - group: Elementary School
  - group: Bachelors
  - group: Father's Friends
  - group: Friends
  - group: High School
  - group: High School Teachers
  - group: Masters
  - group: Neighbours
  - group: Resala
  - group: Tempo
  - group: Valeo
